---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: Install apt packages for nginx and pip3
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - nginx
    - python3-pip

- name: Ensure the standard nginx.conf file is present and accounted for.
  copy:
    src: standardnginx.conf
    dest: /etc/nginx/nginx.conf

- name: copy the requirements file over
  copy:
    src: requirements.txt
    dest: /tmp/requirements.txt

- name: pip install the required python3 libs (including uwsgi)
  pip:
    executable: pip3
    requirements: /tmp/requirements.txt
